// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../../games/domain/models.js";

export function CheckResult(input: domain$0.CheckResultInput): $CancellablePromise<domain$0.GameResult | null> {
    return $Call.ByID(2968119712, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateGame(input: domain$0.CreateGameInput): $CancellablePromise<domain$0.GameSession | null> {
    return $Call.ByID(3179563245, input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Hint(sessionID: string, input: domain$0.HintInput): $CancellablePromise<domain$0.HintResult | null> {
    return $Call.ByID(3075733070, sessionID, input).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListGames(): $CancellablePromise<domain$0.GameMetadata[]> {
    return $Call.ByID(2334862490).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = domain$0.GameResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = domain$0.GameSession.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = domain$0.HintResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = domain$0.GameMetadata.createFrom;
const $$createType7 = $Create.Array($$createType6);
