// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

export class CheckResultInput {
    "gameId": string;
    "sessionId": string;
    "answer": { [_ in string]?: any };

    /** Creates a new CheckResultInput instance. */
    constructor($$source: Partial<CheckResultInput> = {}) {
        if (!("gameId" in $$source)) {
            this["gameId"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("answer" in $$source)) {
            this["answer"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckResultInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CheckResultInput {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("answer" in $$parsedSource) {
            $$parsedSource["answer"] = $$createField2_0($$parsedSource["answer"]);
        }
        return new CheckResultInput($$parsedSource as Partial<CheckResultInput>);
    }
}

export type CreateConfig = { [_ in string]?: any };

export class CreateGameInput {
    "gameId": string;
    "config"?: CreateConfig;

    /** Creates a new CreateGameInput instance. */
    constructor($$source: Partial<CreateGameInput> = {}) {
        if (!("gameId" in $$source)) {
            this["gameId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateGameInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateGameInput {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField1_0($$parsedSource["config"]);
        }
        return new CreateGameInput($$parsedSource as Partial<CreateGameInput>);
    }
}

export class GameMetadata {
    "id": string;
    "name": string;
    "description": string;
    "tags": string[];
    "difficulty": string;
    "viewKind": string;
    "inputSchema": InputField[];
    "defaults": CreateConfig;

    /** Creates a new GameMetadata instance. */
    constructor($$source: Partial<GameMetadata> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("difficulty" in $$source)) {
            this["difficulty"] = "";
        }
        if (!("viewKind" in $$source)) {
            this["viewKind"] = "";
        }
        if (!("inputSchema" in $$source)) {
            this["inputSchema"] = [];
        }
        if (!("defaults" in $$source)) {
            this["defaults"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameMetadata instance from a string or object.
     */
    static createFrom($$source: any = {}): GameMetadata {
        const $$createField3_0 = $$createType2;
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        if ("inputSchema" in $$parsedSource) {
            $$parsedSource["inputSchema"] = $$createField6_0($$parsedSource["inputSchema"]);
        }
        if ("defaults" in $$parsedSource) {
            $$parsedSource["defaults"] = $$createField7_0($$parsedSource["defaults"]);
        }
        return new GameMetadata($$parsedSource as Partial<GameMetadata>);
    }
}

export class GameResult {
    "correct": boolean;
    "message": string;
    "score": number;
    "expected"?: { [_ in string]?: any };
    "session"?: GameSession | null;

    /** Creates a new GameResult instance. */
    constructor($$source: Partial<GameResult> = {}) {
        if (!("correct" in $$source)) {
            this["correct"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GameResult {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("expected" in $$parsedSource) {
            $$parsedSource["expected"] = $$createField3_0($$parsedSource["expected"]);
        }
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField4_0($$parsedSource["session"]);
        }
        return new GameResult($$parsedSource as Partial<GameResult>);
    }
}

export class GameSession {
    "id": string;
    "gameId": string;
    "title": string;
    "prompt": string;
    "state": { [_ in string]?: any };
    "createdAt": time$0.Time;

    /** Creates a new GameSession instance. */
    constructor($$source: Partial<GameSession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("gameId" in $$source)) {
            this["gameId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = {};
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameSession instance from a string or object.
     */
    static createFrom($$source: any = {}): GameSession {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("state" in $$parsedSource) {
            $$parsedSource["state"] = $$createField4_0($$parsedSource["state"]);
        }
        return new GameSession($$parsedSource as Partial<GameSession>);
    }
}

export class HintInput {
    "level": number;

    /** Creates a new HintInput instance. */
    constructor($$source: Partial<HintInput> = {}) {
        if (!("level" in $$source)) {
            this["level"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HintInput instance from a string or object.
     */
    static createFrom($$source: any = {}): HintInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HintInput($$parsedSource as Partial<HintInput>);
    }
}

export class HintResult {
    "message": string;
    "cost": number;

    /** Creates a new HintResult instance. */
    constructor($$source: Partial<HintResult> = {}) {
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("cost" in $$source)) {
            this["cost"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HintResult instance from a string or object.
     */
    static createFrom($$source: any = {}): HintResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HintResult($$parsedSource as Partial<HintResult>);
    }
}

export class InputField {
    "name": string;
    "label": string;
    "type": string;
    "required": boolean;
    "options"?: string[];
    "placeholder"?: string;

    /** Creates a new InputField instance. */
    constructor($$source: Partial<InputField> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("required" in $$source)) {
            this["required"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InputField instance from a string or object.
     */
    static createFrom($$source: any = {}): InputField {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField4_0($$parsedSource["options"]);
        }
        return new InputField($$parsedSource as Partial<InputField>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
var $$createType1 = (function $$initCreateType1(...args: any[]): any {
    if ($$createType1 === $$initCreateType1) {
        $$createType1 = $$createType0;
    }
    return $$createType1(...args);
});
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = InputField.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = GameSession.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
